# Generated by Django 6.1 on 2026-09-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('completed', 'Completed')], default='proposed', max_length=20),
        ),
    ]
