# Generated by Django 6.1 on 2026-09-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_thesis_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
